services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: aegis
      POSTGRES_PASSWORD: aegis_dev_only
      POSTGRES_DB: aegis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../../schemas/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aegis"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    environment:
      AEGIS_DATABASE_URL: postgresql+asyncpg://aegis:aegis_dev_only@postgres:5432/aegis
      AEGIS_REDIS_URL: redis://redis:6379/0
      AEGIS_ENV: development
      AEGIS_PERSIST_FINDINGS: "true"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    command: ["python", "-m", "aegis.messaging.worker"]
    environment:
      AEGIS_DATABASE_URL: postgresql+asyncpg://aegis:aegis_dev_only@postgres:5432/aegis
      AEGIS_REDIS_URL: redis://redis:6379/0
      AEGIS_ENV: development
      AEGIS_PERSIST_FINDINGS: "true"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      api:
        condition: service_started

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: aegis_dev_only
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ../../deploy/grafana/provisioning:/etc/grafana/provisioning:ro
      - ../../deploy/grafana/aegis-overview.json:/var/lib/grafana/dashboards/aegis-overview.json:ro
    depends_on:
      - postgres

volumes:
  pgdata:
