apiVersion: 1
datasources:
  - name: AEGIS-Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: aegis
    user: aegis
    secureJsonData:
      password: aegis_dev_only
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
