"""Signed audit export — HMAC-SHA256 over canonical JSON of audit rows."""
from __future__ import annotations

import hashlib
import hmac
import json
import os
from datetime import datetime, timezone
from typing import Any


def utcnow_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def canonical_json(obj: Any) -> str:
    return json.dumps(obj, sort_keys=True, default=str, separators=(",", ":"))


def sign_payload(payload: dict[str, Any], secret: str) -> str:
    body = canonical_json(payload)
    return hmac.new(secret.encode("utf-8"), body.encode("utf-8"), hashlib.sha256).hexdigest()


def verify_signature(payload: dict[str, Any], signature: str, secret: str) -> bool:
    expected = sign_payload(payload, secret)
    return hmac.compare_digest(expected, signature)


def build_signed_export(
    rows: list[dict[str, Any]],
    *,
    secret: str | None = None,
    engagement_id: str | None = None,
) -> dict[str, Any]:
    secret = secret or os.getenv("AEGIS_AUDIT_SIGNING_KEY") or None
    payload = {
        "schema": "aegis.audit.export.v1",
        "exported_at": utcnow_iso(),
        "engagement_id": engagement_id,
        "count": len(rows),
        "entries": rows,
    }
    if not secret:
        return {**payload, "signature": None, "signing": "unsigned"}
    sig = sign_payload(payload, secret)
    return {**payload, "signature": sig, "signing": "hmac-sha256"}


def render_executive_html(
    *,
    engagement_name: str,
    engagement_id: str,
    summary: str,
    severity_counts: dict[str, int],
    top_findings: list[dict[str, Any]],
    coverage: dict[str, Any] | None = None,
) -> str:
    rows = ""
    for f in top_findings[:10]:
        title = f.get("title") or f.get("finding_id") or "finding"
        sev = f.get("severity", "info")
        risk = f.get("risk_score", "")
        rows += f"<tr><td>{sev}</td><td>{title}</td><td>{risk}</td></tr>"
    cov = ""
    if coverage:
        cov = f"<p>ATT&amp;CK coverage: {coverage.get('coverage_pct', 0)}% ({coverage.get('covered')}/{coverage.get('total_techniques')} techniques)</p>"
    sev_line = ", ".join(f"{k}={v}" for k, v in severity_counts.items())
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <title>AEGIS Executive Report — {engagement_name}</title>
  <style>
    body {{ font-family: system-ui, sans-serif; margin: 2rem; color: #0f172a; }}
    h1 {{ font-size: 1.5rem; }}
    .meta {{ color: #64748b; font-size: 0.9rem; }}
    table {{ border-collapse: collapse; width: 100%; margin-top: 1rem; }}
    th, td {{ border: 1px solid #e2e8f0; padding: 0.5rem 0.75rem; text-align: left; }}
    th {{ background: #f1f5f9; }}
    .summary {{ background: #f8fafc; padding: 1rem; border-radius: 8px; }}
  </style>
</head>
<body>
  <h1>AEGIS Executive Report</h1>
  <p class="meta">Engagement: {engagement_name} · ID: {engagement_id}</p>
  <div class="summary"><p>{summary}</p><p>Severity: {sev_line}</p>{cov}</div>
  <h2>Top findings</h2>
  <table>
    <thead><tr><th>Severity</th><th>Title</th><th>Risk</th></tr></thead>
    <tbody>{rows or "<tr><td colspan=3>No findings</td></tr>"}</tbody>
  </table>
  <p class="meta">Generated by AEGIS Swarm · authorized defensive use only</p>
</body>
</html>
"""
